docker run --detach \
 --name influxdb2 \
 --publish 8086:8086 \
 --mount type=volume,source=influxdb2-data,target=/var/lib/influxdb2 \
 --mount type=volume,source=influxdb2-config,target=/etc/influxdb2 \
 --env DOCKER_INFLUXDB_INIT_MODE=setup \
 --env DOCKER_INFLUXDB_INIT_USERNAME=mark \
 --env DOCKER_INFLUXDB_INIT_PASSWORD=P@ss@t2004 \
 --env DOCKER_INFLUXDB_INIT_ORG=Restivo.co \
 --env DOCKER_INFLUXDB_INIT_BUCKET=home \
 influxdb:2