---
- name: Deploy Pi-hole using Docker Compose
  hosts: managers
  become: yes
  vars:
    compose_file_path: "/home/ansible/docker/pihole/docker-compose_pi-hole.yml" # this will need to be changed on new setups
    compose_directory: "/home/ansible/docker/pihole"

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.command:
        cmd: docker --version
      failed_when: false
      register: docker_installed

    - name: Fail if Docker is not installed
      ansible.builtin.fail:
        msg: "Docker is not installed on the target machine. Please install Docker first."
      when: "'Docker version' not in docker_installed.stdout"

    - name: Ensure Docker Compose is installed
      ansible.builtin.command:
        cmd: docker-compose --version
      failed_when: false
      register: compose_installed

    - name: Fail if Docker Compose is not installed
      ansible.builtin.fail:
        msg: "Docker Compose is not installed on the target machine. Please install Docker Compose first."
      when: "'docker-compose version' not in compose_installed.stdout"

    - name: Ensure compose directory exists
      ansible.builtin.file:
        path: "{{ compose_directory }}"
        state: directory
        mode: '0755'

    - name: Create the Docker Compose file for Pi-hole
      ansible.builtin.copy:
        dest: "{{ compose_file_path }}"
        content: |
          version: "3.8"
          services:
            pihole:
              container_name: pihole
              image: pihole/pihole:latest
              ports:
                - "53:53/tcp"
                - "53:53/udp"
                - "67:67/udp"
                - "80:80/tcp"
              environment:
                TZ: 'America/Chicago'
              volumes:
                - './etc-pihole:/etc/pihole'
                - './etc-dnsmasq.d:/etc/dnsmasq.d'
              cap_add:
                - NET_ADMIN
              restart: unless-stopped
        mode: '0644'

    - name: Deploy Pi-hole container using Docker Compose
      ansible.builtin.shell:
        cmd: "docker-compose -f {{ compose_file_path }} up -d"
      args:
        chdir: "{{ compose_directory }}"
      register: compose_output

    - name: Display Docker Compose output
      debug:
        var: compose_output.stdout

    - name: Verify Pi-hole service is running
      ansible.builtin.command:
        cmd: docker ps --filter "name=pihole"
      register: docker_ps_output

    - name: Display running Pi-hole container
      debug:
        var: docker_ps_output.stdout
