---
- name: Configure Certbot for Automatic Renewal
  hosts: managers
  become: yes
  vars:
    nginx_reload_script: "/home/mark/ansible/docker/reload-nginx.sh" # this will need to chang on new setups

  tasks:
    - name: Ensure Certbot is installed
      ansible.builtin.apt:
        name: certbot
        state: present
        update_cache: yes

    - name: Verify Certbot installation
      ansible.builtin.command:
        cmd: certbot --version
      register: certbot_version
      failed_when: "'certbot' not in certbot_version.stdout"

    - name: Enable Certbot renewal timer
      ansible.builtin.systemd:
        name: certbot.timer
        enabled: yes
        state: started

    - name: Verify Certbot renewal configuration
      ansible.builtin.command:
        cmd: certbot renew --dry-run
      register: renewal_check
      failed_when: "'No renewals were attempted' in renewal_check.stdout or 'Failed' in renewal_check.stderr"

    - name: Ensure directory for deploy hooks exists
      ansible.builtin.file:
        path: "/etc/letsencrypt/renewal-hooks/deploy"
        state: directory
        mode: '0755'

    - name: Create Nginx reload hook script
      ansible.builtin.copy:
        dest: "{{ nginx_reload_script }}"
        content: |
          #!/bin/bash
          systemctl reload nginx
        mode: '0755'

    - name: Test Nginx reload hook script
      ansible.builtin.command:
        cmd: "{{ nginx_reload_script }}"
      register: nginx_reload_test
      failed_when: "'failed' in nginx_reload_test.stderr"
      changed_when: false

    - name: Display renewal dry-run result
      debug:
        var: renewal_check.stdout
