---
- name: Install Docker using Docker's official script
  hosts: RPi
  become: yes
  tasks:
    - name: Ensure prerequisites are installed
      apt:
        name:
          - curl
        update_cache: yes

    - name: Download and run the Docker installation script
      shell: curl -sSL https://get.docker.com | sh
      args:
        executable: /bin/bash

    - name: Add current user to the docker group
      user:
        name: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
        groups: docker
        append: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes
