global:
  resolve_timeout: 5m

route:
  # Grouping and routing configuration
  group_by: ['alertname', 'cluster', 'job', 'environment', 'severity']
  repeat_interval: 24h
  group_interval: 5m
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'mjrestivo15@outlook.com'  # Your email to receive alerts
        from: 'AlertManager <mjrestivo16@gmail.com>'  # Sender name and email
        smarthost: 'smtp.gmail.com:587'  # Gmail SMTP server and port
        require_tls: true
        auth_username: 'mjrestivo16@gmail.com'  # Your Gmail address
        auth_password: 'pdsh rtii jkyz vrkf'  # Your Gmail app-specific password
        hello: 'alertmanager'
